#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TtsSetup.Resource", IsApplication=true)]

namespace TtsSetup
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int tts_quality = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int tts_samples = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int add_lang_btn = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int add_voice = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int eng_quality = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int eng_search = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int languages = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int main = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int progressBar = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int sel_lang = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int setupButton = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int testButton = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int tts_engines = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int use_voice_btn = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int voices = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int wait = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int wait_msg = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int add_lang_voice = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int voice_sel = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000b
			public const int add_lang = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int add_new1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int add_new2 = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int add_new_voice = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int choose_tts = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int eng_quality = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int eng_search = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int go_back = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int new_eng_search = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int no_inst_data = 2131034133;
			
			// aapt resource value: 0x7f050001
			public const int please_wait = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int sel_lang1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int sel_lang2 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int sel_voice = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int sys_def_tts = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int tts_inst_no = 2131034134;
			
			// aapt resource value: 0x7f050006
			public const int tts_langs = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int tts_voices = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int use_voice = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int vsearch1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int vsearch2 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int vsearch3 = 2131034128;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
